<?php
include_once('../FirePHPCore/fb.php');
include_once('../FirePHPCore/FirePHP.class.php');
include_once('../dal/general.php');
include_once('../dal/log.php');
include_once('../dal/buildings.php');
include_once('../dal/user.php');
include_once('../dal/map.php');
include_once('../dal/login.php');
include_once('../bl/general.php');
include_once('../bl/log.php');
include_once('../bl/wikiparser.php');
include_once('../bl/class.phpmailer.php');
include_once('../bl/ajax.php');
include_once('../bl/user.class.php');
include_once('../util/mysql.php');
include_once('../util/html.php');
include_once('../util/math.php');
?>