<?php
include_once('lib/FirePHPCore/fb.php');
include_once('lib/FirePHPCore/FirePHP.class.php');
include_once('lib/dal/general.php');
include_once('lib/dal/buildings.php');
include_once('lib/dal/user.php');
include_once('lib/dal/map.php');
include_once('lib/dal/login.php');
include_once('lib/bl/general.php');
include_once('lib/bl/log.inc.php');
include_once('lib/bl/wikiparser.php');
include_once('lib/bl/class.phpmailer.php');
include_once('lib/bl/user.class.php');
include_once('lib/bl/user.php');
include_once('lib/util/mysql.php');
include_once('lib/util/html.php');
include_once('lib/util/math.php');
include_once('lib/smarty/Smarty.class.php');