<?php
require_once(__DIR__.'/../dal/unit.php');
require_once(__DIR__.'/../dal/unit_train.php');
require_once(__DIR__.'/../dal/general.php');
require_once(__DIR__.'/../dal/user.php');
require_once(__DIR__.'/../dal/troops.php');
require_once(__DIR__.'/../dal/buildings.php');
require_once(__DIR__.'/../bl/unit.php');
require_once(__DIR__.'/../bl/unit_move.php');
require_once(__DIR__.'/../bl/unit_train.php');
require_once(__DIR__.'/../bl/general.php');
require_once(__DIR__.'/../bl/troops.php');
require_once(__DIR__.'/../bl/buildings.php');