CREATE TABLE `dw_unit_stats` (
	`usid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`kind` TINYINT NOT NULL, 
	`strength` TINYINT NOT NULL, 
	`moral` TINYINT NOT NULL, 
	`agility` TINYINT NOT NULL, 
	`armor` TINYINT NOT NULL, 
	`speed` TINYINT NOT NULL
) ENGINE = MyISAM;
CREATE TABLE `dw_building_stats` (`bsid` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, `kind` TINYINT UNSIGNED NOT NULL, `upgrade_lvl` TINYINT UNSIGNED NOT NULL, `defense` INT UNSIGNED NOT NULL, `attack` INT UNSIGNED NOT NULL) ENGINE = MyISAM;