ALTER TABLE `dw_res`
	CHANGE COLUMN `food` `food` BIGINT NOT NULL DEFAULT '1000' AFTER `map_y`,
	CHANGE COLUMN `wood` `wood` BIGINT NOT NULL DEFAULT '1000' AFTER `food`,
	CHANGE COLUMN `rock` `rock` BIGINT NOT NULL DEFAULT '1000' AFTER `wood`,
	CHANGE COLUMN `iron` `iron` BIGINT NOT NULL DEFAULT '250' AFTER `rock`,
	CHANGE COLUMN `paper` `paper` BIGINT NOT NULL DEFAULT '0' AFTER `iron`,
	CHANGE COLUMN `koku` `koku` BIGINT NOT NULL DEFAULT '0' AFTER `paper`;